### ISSUE TITLE
zip文件中网页链接错误

### ISSUE THREAD

**Issue by tryeverything** [xuxiaodong/gitimmersion#1]
下载了zip文件，解压后，打开contents.html，点击里面链接均提示错误

Firefox can't find the file at /C:/Users/cike/Desktop/gitimmersion-gh-pages/gitimmersion-gh-pages/{{ site.baseurl }}setup.html.

**Comment by xuxiaodong** [comment]
这个源代码是仅供于 GitHub Pages 使用的，不是从本地浏览的。请使用 http://igit.linuxtoy.org/contents.html 访问。

若需本地访问，需安装 [Jekyll](http://jekyllrb.com/)。

**Comment by tryeverything** [comment]
原来是这样啊。呵呵，明白了。感谢告知:)

在 2014年4月28日 上午9:01，Xiaodong Xu notifications@github.com写道：
